# fly.toml app configuration file generated for mynameinkanji on 2023-09-05T16:01:18+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mynameinkanji"
primary_region = "nrt"
console_command = "/code/manage.py shell"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/staticfiles"
  url_prefix = "/static/"
